/** Todos os textos da interface ficam aqui, para manter o mesmo vocabulário em todas as telas. */
export const T = {
  app: { nome: 'Cronogramas EaD', apoio: 'Unidigit@l · Planejamento de turmas' },
  nav: { inicio: 'Início', cronograma: 'Cronogramas', turmas: 'Turmas', cursos: 'Cursos', equipe: 'Equipe', acessos: 'Acessos', unidades: 'Unidades', feriados: 'Feriados', backup: 'Backup', config: 'Configurações' },
  /** Categorias de curso do SENAI (formação inicial e continuada, técnica de nível médio e superior). `min`/`max` são cargas horárias de referência. */
  categoriaGrupos: [
    { nome: 'Formação inicial e continuada', itens: ['iniciacao', 'aprendizagem_basica', 'qualificacao', 'aperfeicoamento', 'especializacao_prof', 'curso_livre'] },
    { nome: 'Educação profissional técnica de nível médio', itens: ['aprendizagem_tecnica', 'tecnico'] },
    { nome: 'Educação superior e pós-graduação', itens: ['graduacao_tecnologica', 'graduacao', 'pos_graduacao', 'mestrado_doutorado'] },
  ] as { nome: string; itens: string[] }[],
  categoria: {
    iniciacao: { nome: 'Iniciação Profissional', desc: 'Competências básicas para o trabalho, para jovens e adultos de qualquer escolaridade.', max: 160 },
    aprendizagem_basica: { nome: 'Aprendizagem Industrial Básica', desc: 'Formação para jovens aprendizes (a partir de 14 anos), com contrato de aprendizagem.', min: 400 },
    qualificacao: { nome: 'Qualificação Profissional', desc: 'Formação para atuar em uma ocupação do mercado (formação inicial e continuada).', min: 160 },
    aperfeicoamento: { nome: 'Aperfeiçoamento Profissional', desc: 'Atualização e aprofundamento para quem já atua na área.' },
    especializacao_prof: { nome: 'Especialização Profissional', desc: 'Formação aprofundada em área específica, para quem já tem formação anterior (não é pós-graduação).' },
    curso_livre: { nome: 'Curso livre', desc: 'Cursos rápidos, sem exigência de escolaridade, com certificado de participação.' },
    aprendizagem_tecnica: { nome: 'Aprendizagem Industrial Técnica de Nível Médio', desc: 'Curso técnico para jovens aprendizes, com contrato de aprendizagem.', min: 800 },
    tecnico: { nome: 'Técnico de Nível Médio', desc: 'Para quem está cursando ou concluiu o ensino médio. Em geral de 18 a 24 meses.', min: 800 },
    graduacao_tecnologica: { nome: 'Graduação Tecnológica', desc: 'Curso superior de tecnologia, em geral de 2 a 3 anos.' },
    graduacao: { nome: 'Graduação', desc: 'Bacharelado ou licenciatura em faculdade SENAI.' },
    pos_graduacao: { nome: 'Pós-graduação', desc: 'Especialização (lato sensu) para quem já tem curso superior.' },
    mestrado_doutorado: { nome: 'Mestrado e doutorado', desc: 'Pós-graduação stricto sensu (profissional ou acadêmica).' },
  } as unknown as Record<string, { nome: string; desc: string; min?: number; max?: number }>,
  modalidade: { ead: 'EaD (100% Online)', semipresencial: 'Semipresencial / Híbrido' } as Record<string, string>,
  modalidadeLonga: { ead: 'EaD (100% Online)', semipresencial: 'Semipresencial / Híbrido' } as Record<string, string>,
  inicio: {
    titulo: 'Início', subEquipe: 'Como estão os cronogramas e o que precisa da sua atenção.', subUnidade: 'Como estão as turmas da sua unidade e o que espera a sua validação.',
    status: 'Cronogramas por status', acao: 'Precisa de ação agora', acaoVazio: 'Nada pendente. Tudo em dia.', unidade: 'Por unidade', atividade: 'Atividade recente', atividadeVazio: 'Ainda sem atividade registrada.', marcos: 'Próximos marcos', marcosVazio: 'Nada marcado para os próximos 45 dias.',
  },
  config: {
    titulo: 'Configurações',
    sub: 'Tudo o que organiza o sistema, mas não é o dia a dia dos cronogramas.',
    itens: {
      equipe: { nome: 'Equipe', desc: 'Monitores, tutores e coordenadores' },
      acessos: { nome: 'Acessos', desc: 'Quem entra no sistema e com qual perfil' },
      unidades: { nome: 'Unidades', desc: 'Unidades escolares atendidas' },
      feriados: { nome: 'Feriados', desc: 'Dias sem aula usados no cálculo das datas' },
      integracoes: { nome: 'Integrações', desc: 'Serviços externos e credenciais técnicas' },
      backup: { nome: 'Backup', desc: 'Exportar e restaurar os dados' },
    },
  },
  cron: {
    titulo: 'Cronograma',
    turma: 'Turma',
    copiar: 'Copiar para Excel',
    copiado: 'Tabela copiada. Cole no Excel ou no Google Planilhas.',
    semTurma: { titulo: 'Nenhuma turma cadastrada', texto: 'O cronograma é gerado a partir de uma turma. Crie a primeira em Turmas.', acao: 'Criar turma' },
    semCurso: { titulo: 'Esta turma está sem curso', texto: 'Escolha um curso para a turma na página Turmas.', acao: 'Abrir Turmas' },
    visao: { tabela: 'Tabela', linha: 'Linha do tempo' },
    grupos: { prazos: 'Prazos no AVA', equipe: 'Equipe', encontros: 'Encontros presenciais', presencial: 'Presencial', suporte: 'Suporte Unidigital' },
    resumo: { inicio: 'Início', fim: 'Término previsto', ch: 'Carga horária', ucs: 'Unidades curriculares', enc: 'Encontros presenciais', hoje: 'Em andamento hoje', nenhuma: 'Nenhuma UC em andamento' },
    verif: { titulo: 'Verificações', tudoCerto: 'Tudo certo com as regras do curso.', alertas: (n: number) => `${n} ${n === 1 ? 'ponto' : 'pontos'} para conferir` },
    sit: { concluida: 'Concluída', andamento: 'Em andamento', aIniciar: 'A iniciar', semData: 'Sem data' },
    legenda: 'Datas de início, término, AVA, webconferência e postagem são calculadas. Para mudar a estrutura, edite o curso em Cursos.',
    padrao: (nome: string) => `Padrão: ${nome}`,
    semInicio: 'Informe a data de início da turma (campo "Início da turma", acima) para calcular os prazos e sugerir os encontros.',
  },
  turmas: {
    titulo: 'Turmas', nova: 'Nova turma', solicitar: 'Solicitar turma', mostrarArquivadas: 'Mostrar turmas arquivadas', vazioUnidade: 'Sua unidade ainda não tem turmas. Peça uma nova turma com o botão acima.', criada: 'Turma criada.', solicitada: 'Pedido enviado. A Unidigit@l recebeu um aviso.', novaTexto: 'A turma nasce em elaboração: só a Unidigit@l a vê até você enviá-la para a unidade validar.', solicitarTexto: 'Informe o curso e a data em que você precisa da turma. A Unidigit@l monta o cronograma e avisa você para validar.', ajudaUnidade: 'Você pode ajustar ambiente, coordenador e professor, e as datas dos encontros no cronograma, enquanto ele estiver aguardando a sua validação.', dados: 'Dados da turma', abrir: 'Abrir cronograma', duplicar: 'Duplicar', excluir: 'Excluir turma',
    vazio: { titulo: 'Nenhuma turma ainda', texto: 'Crie uma turma para começar a gerar cronogramas.' },
    ajuda: 'Estes dados valem para todas as linhas do cronograma. Na página Cronograma você troca monitor, tutor, evento e outros campos de uma linha específica.',
    confirma: (n: string) => ({ titulo: `Excluir a turma “${n}”?`, texto: 'O cronograma e as datas dos encontros dessa turma serão apagados. Não é possível desfazer.', ok: 'Excluir turma', voltar: 'Manter turma' }),
    duplicada: 'Turma duplicada.',
  },
  cursos: {
    titulo: 'Cursos', novo: 'Novo curso', dados: 'Dados do curso', regras: 'Regras de datas', modulo: 'Módulo', addModulo: 'Adicionar módulo',
    addUC: 'UC', addRec: 'Recuperação', addMat: 'Matrícula',
    semUso: 'Este módulo ainda não tem etapas. Use os botões UC, Recuperação ou Matrícula para adicionar.',
    ajuda: 'Cada UC começa no dia útil seguinte ao término da UC anterior. A Recuperação começa quando a UC que ela recupera termina e corre junto com a UC seguinte. A Matrícula vem depois da última recuperação do módulo. Dias de estudo EaD = CH a distância ÷ divisor, arredondado para cima; com 21 h a distância, são 7 dias.',
    confirmaCurso: (n: string) => ({ titulo: `Excluir o curso “${n}”?`, texto: 'Os módulos e as unidades curriculares serão apagados. Não é possível desfazer.', ok: 'Excluir curso', voltar: 'Manter curso' }),
    confirmaModulo: (n: string) => ({ titulo: `Excluir o módulo “${n}”?`, texto: 'As unidades curriculares do módulo serão apagadas.', ok: 'Excluir módulo', voltar: 'Manter módulo' }),
    emUso: 'Há turmas usando este curso. Exclua as turmas ou troque o curso delas antes.',
    chOk: (s: number, t: number) => `As UCs somam ${s} h, igual ao total do curso (${t} h).`,
    chErro: (s: number, t: number) => `As UCs somam ${s} h, mas o curso tem ${t} h. Ajuste a carga das UCs ou o total do curso.`,
  },
  equipe: {
    titulo: 'Equipe', nome: 'Nome completo', papel: 'Papel', adicionar: 'Adicionar pessoa', adicionada: 'Pessoa adicionada.', informeNome: 'Informe o nome da pessoa.',
    vazio: { titulo: 'Equipe vazia', texto: 'Cadastre monitores, tutores, professores e coordenadores para escolhê-los nas turmas em vez de digitar o nome.' },
    confirma: (n: string) => ({ titulo: `Remover ${n} da equipe?`, texto: 'Essa pessoa deixa de aparecer nas turmas e nos cronogramas.', ok: 'Remover pessoa', voltar: 'Manter pessoa' }),
    papeis: { monitor: 'Monitores', tutor: 'Tutores', professor: 'Professores presenciais', coordenador: 'Coordenadores técnicos' },
    papel1: { monitor: 'Monitor', tutor: 'Tutor', professor: 'Professor presencial', coordenador: 'Coordenador técnico' },
  },
  feriados: {
    titulo: 'Feriados, recessos e férias', ano: 'Ano', data: 'Data', motivo: 'Motivo', adicionar: 'Adicionar data',
    ajuda: 'Estas datas não contam como dia útil nos prazos. Sábados e domingos já são ignorados.',
    valeEm: 'Vale para', todas: 'Todas as unidades', ajudaUnidade: 'Feriados municipais valem só para esta unidade, além dos feriados gerais (em laranja claro).',
    escolhaData: 'Escolha a data.', jaExiste: 'Essa data já está na lista.', adicionada: 'Data adicionada. Os prazos foram recalculados.',
    padrao: 'Feriado', legenda: 'Dias marcados no calendário não contam como dia útil.',
  },
  backup: {
    titulo: 'Cópia dos dados',
    ajuda: 'Baixe uma cópia de cursos, equipe, feriados, unidades e turmas para guardar. Para voltar a uma cópia, escolha o arquivo e clique em Carregar. Carregar troca o cadastro e atualiza as turmas que ainda não foram validadas; turmas já validadas ou enviadas à unidade não são tocadas.',
    baixar: 'Baixar cópia (.json)', baixou: 'Cópia baixada.', escolher: 'Escolher arquivo .json', carregar: 'Carregar cópia', carregado: (n: number, p: number) => `Cópia carregada: ${n} ${n === 1 ? 'turma atualizada' : 'turmas atualizadas'}${p ? `, ${p} ${p === 1 ? 'preservada' : 'preservadas'} por já estarem em validação` : ''}.`,
    invalido: 'Não foi possível ler este arquivo. Use uma cópia baixada deste sistema.',
    confirma: { titulo: 'Carregar esta cópia?', texto: 'Cursos, equipe, feriados e unidades atuais serão substituídos. Turmas em elaboração são atualizadas; turmas em validação ou validadas ficam como estão. Não é possível desfazer.', ok: 'Carregar cópia', voltar: 'Cancelar' },
  },
  geral: { cancelar: 'Cancelar', nenhum: '—', salvo: 'Tudo salvo', salvando: 'Salvando…', sujo: 'Alterações a salvar', erro: 'Não foi possível salvar', sair: 'Sair' },
  status: { solicitado: 'Solicitada', elaboracao: 'Em elaboração', validacao: 'Aguardando validação', validado: 'Validado', arquivado: 'Arquivado' } as Record<string, string>,
  perfil: { equipe: 'Unidigit@l', unidade: 'Unidade escolar', consulta: 'Consulta' } as Record<string, string>,
  fluxo: {
    msg: {
      equipe: {
        solicitado: (u: string) => `A unidade ${u} pediu esta turma. Aceite para começar a montar o cronograma.`,
        elaboracao: () => 'Só a Unidigit@l vê este cronograma por enquanto. Quando estiver pronto, envie para a unidade validar.',
        validacao: (u: string, prazo: string) => `Com a unidade ${u}${prazo ? `, prazo até ${prazo}` : ''}. A unidade ajusta datas dos encontros, ambiente, professor e coordenador; você acompanha o que mudou no histórico.`,
        validado: (v: number, por: string, em: string) => `Versão ${v} validada${por ? ` por ${por}` : ''}${em ? ` em ${em}` : ''}. O cronograma está travado. Para mudar algo, reabra e informe o motivo.`,
        arquivado: () => 'Turma arquivada. Restaure para voltar a editar.',
      },
      unidade: {
        solicitado: () => 'Pedido enviado. A Unidigit@l vai começar a montar o cronograma e avisar você.',
        elaboracao: () => 'A Unidigit@l está montando o cronograma. Você recebe um aviso quando for a hora de validar.',
        validacao: (prazo: string) => `Este cronograma espera a sua validação${prazo ? ` até ${prazo}` : ''}. Você pode ajustar as datas dos encontros, o ambiente, o professor e o coordenador. Quando estiver tudo certo, clique em Validar.`,
        validado: (v: number, por: string, em: string) => `Versão ${v} validada${por ? ` por ${por}` : ''}${em ? ` em ${em}` : ''}. Para mudar algo, peça à Unidigit@l.`,
        arquivado: () => 'Esta turma foi arquivada.',
      },
      consulta: 'Você tem acesso só para consulta. Nada aqui pode ser alterado.',
    },
    reaberta: (v: number, vig: number) => `Versão ${v} em revisão. A versão ${vig} continua sendo a vigente até a nova validação.`,
    acoes: {
      iniciar: { rotulo: 'Aceitar e começar', titulo: 'Aceitar a solicitação?', texto: 'A turma passa para elaboração e a unidade é avisada de que você começou.', ok: 'Aceitar e começar' },
      enviar: { rotulo: 'Enviar para validação', titulo: 'Enviar para a unidade validar?', texto: 'A unidade recebe um e-mail e passa a ver este cronograma. Ela poderá ajustar as datas dos encontros, o ambiente, o professor e o coordenador.', ok: 'Enviar para validação' },
      recolher: { rotulo: 'Recolher para ajustes', titulo: 'Recolher o cronograma?', texto: 'A unidade deixa de poder ajustar e o cronograma volta para elaboração.', ok: 'Recolher', motivo: 'Por que está recolhendo?' },
      validar: { rotulo: 'Validar cronograma', titulo: 'Validar este cronograma?', texto: 'Depois da validação ninguém altera as datas, nem a unidade. Só a Unidigit@l pode reabrir, informando o motivo.', ok: 'Validar cronograma', ressalva: 'Ressalva (opcional)', ressalvaDica: 'Algo que você aceita, mas quer deixar registrado.', motivoEquipe: 'Como a unidade confirmou? (e-mail, ofício, reunião…)' },
      reabrir: { rotulo: 'Reabrir para alteração', titulo: 'Reabrir este cronograma?', texto: 'Ele volta para a validação da unidade, numa nova versão. A versão validada continua guardada.', ok: 'Reabrir', motivo: 'Por que está reabrindo?' },
      arquivar: { rotulo: 'Arquivar', titulo: 'Arquivar esta turma?', texto: 'A turma sai da lista de trabalho, mas o histórico e as versões validadas ficam guardados.', ok: 'Arquivar', motivo: 'Motivo do arquivamento' },
      restaurar: { rotulo: 'Restaurar', titulo: 'Restaurar a turma?', texto: 'Ela volta para elaboração.', ok: 'Restaurar' },
      comentarUnidade: { rotulo: 'Pedir alteração à Unidigit@l', titulo: 'O que você precisa mudar?', texto: 'Use para o que você não pode ajustar sozinho, como carga horária ou troca de curso. A Unidigit@l é avisada no sistema e por e-mail.', ok: 'Enviar pedido', motivo: 'Seu pedido' },
      comentarEquipe: { rotulo: 'Enviar mensagem à unidade', titulo: 'Mensagem para a unidade', texto: 'A unidade é avisada no sistema e por e-mail, e a mensagem fica na conversa e no histórico.', ok: 'Enviar mensagem', motivo: 'Mensagem' },
    },
    prazo: 'Prazo para a unidade validar',
    prazoDica: 'A unidade recebe um lembrete um dia antes. Ao vencer, você e a unidade são avisados; nada é validado sozinho.',
    bloqueioEnvio: (n: number) => `Resolva ${n === 1 ? '1 ponto' : `${n} pontos`} em Verificações antes de enviar. O cronograma precisa estar consistente para a unidade validar.`,
    ajustes: { sujo: 'Você tem ajustes ainda não salvos.', salvar: 'Salvar ajustes', descartar: 'Descartar', tituloSalvar: 'Salvar seus ajustes', motivo: 'Por que mudou? (obrigatório quando muda a data de um encontro)', salvos: 'Ajustes salvos. A Unidigit@l pode ver o que mudou.', descartados: 'Ajustes descartados.', salveAntes: 'Salve ou descarte seus ajustes antes de validar.' },
    feito: { iniciar: 'Solicitação aceita.', enviar: 'Enviado para a unidade validar.', recolher: 'Cronograma recolhido.', validar: 'Cronograma validado e travado.', reabrir: 'Cronograma reaberto para validação.', arquivar: 'Turma arquivada.', restaurar: 'Turma restaurada.', comentar: 'Mensagem enviada.' } as Record<string, string>,
    conflito: { titulo: 'Alguém alterou esta turma', ok: 'Entendi' },
  },
  hist: {
    titulo: 'Histórico e versões', vazio: 'Ainda não há registros.', versoes: 'Versões validadas', semVersoes: 'Nenhuma versão validada ainda.', registros: 'Registros',
    acoes: { criar: 'Turma criada', solicitar: 'Turma solicitada', iniciar: 'Elaboração iniciada', enviar: 'Enviado para validação', recolher: 'Recolhido para ajustes', validar: 'Validado', reabrir: 'Reaberto para alteração', arquivar: 'Arquivada', restaurar: 'Restaurada', ajuste: 'Ajustes da unidade', edicao_equipe: 'Edição da Unidigit@l', comentario: 'Mensagem', lembrete: 'Lembrete de prazo', email_falhou: 'E-mail não enviado', pedido_atendido: 'Pedido atendido', atraso: 'Prazo vencido', excluir: 'Excluída' } as Record<string, string>,
  },
  exportar: { excel: 'Baixar Excel', pdf: 'Baixar PDF', gerando: 'Gerando…', pronto: (n: string) => `${n} gerado.`, falha: 'Não foi possível gerar o arquivo.', bloqueado: 'O navegador bloqueou o download. Permita downloads para este site e tente de novo.' },
  unidades: {
    titulo: 'Unidades escolares', nome: 'Nome da unidade', cidade: 'Cidade', adicionar: 'Adicionar unidade', adicionada: 'Unidade adicionada.', informeNome: 'Informe o nome da unidade.',
    ajuda: 'Cada turma pertence a uma unidade. As pessoas da unidade só enxergam as turmas dela, e os feriados municipais valem só para ela. Para dar acesso, crie o usuário no WordPress e marque a unidade no perfil dele.',
    vazio: { titulo: 'Nenhuma unidade ainda', texto: 'Cadastre a primeira unidade escolar para poder criar turmas.' },
    emUso: 'Há turmas desta unidade. Exclua ou arquive as turmas antes de remover a unidade.',
    confirma: (n: string) => ({ titulo: `Remover a unidade “${n}”?`, texto: 'Ela deixa de aparecer na lista. Os feriados municipais dela também serão apagados.', ok: 'Remover unidade', voltar: 'Manter unidade' }),
  },
}
